x-logging: &default-logging
  driver: loki
  options:
    loki-url: http://localhost:3100/loki/api/v1/push
    loki-retries: 5
    loki-batch-size: 400

services:
  loki:
    image: grafana/loki:2.9.2
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    logging: *default-logging
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.9.2
    volumes:
      - /var/log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers
      - ./configs/promtail.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki

  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    logging: *default-logging
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy 
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - loki
  
  # Override the logging config for the services in the main docker compose
  ngrok-icredy-agent:
    logging: *default-logging

  icredy-acapy-image-builder:
    logging: *default-logging

  icredy-agent:
    logging: *default-logging

  icredy-db:
    logging: *default-logging

  tenant-proxy:
    logging: *default-logging 

  endorser-agent:
    logging: *default-logging

  endorser-db:
    logging: *default-logging

  endorser-agent-1:
    logging: *default-logging
    

networks:
  loki: